//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowQueen.SnowQueenService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MainModel", Namespace="http://schemas.datacontract.org/2004/07/WCFService.Model")]
    [System.SerializableAttribute()]
    public partial class MainModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int countField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                if ((this.countField.Equals(value) != true)) {
                    this.countField = value;
                    this.RaisePropertyChanged("count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SnowQueenService.IShowData")]
    public interface IShowData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowData/Show", ReplyAction="http://tempuri.org/IShowData/ShowResponse")]
        SnowQueen.SnowQueenService.MainModel[] Show();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowData/Show", ReplyAction="http://tempuri.org/IShowData/ShowResponse")]
        System.Threading.Tasks.Task<SnowQueen.SnowQueenService.MainModel[]> ShowAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShowDataChannel : SnowQueen.SnowQueenService.IShowData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShowDataClient : System.ServiceModel.ClientBase<SnowQueen.SnowQueenService.IShowData>, SnowQueen.SnowQueenService.IShowData {
        
        public ShowDataClient() {
        }
        
        public ShowDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShowDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShowDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShowDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SnowQueen.SnowQueenService.MainModel[] Show() {
            return base.Channel.Show();
        }
        
        public System.Threading.Tasks.Task<SnowQueen.SnowQueenService.MainModel[]> ShowAsync() {
            return base.Channel.ShowAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SnowQueenService.IAddData")]
    public interface IAddData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddData/Add", ReplyAction="http://tempuri.org/IAddData/AddResponse")]
        void Add(SnowQueen.SnowQueenService.MainModel mainModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddData/Add", ReplyAction="http://tempuri.org/IAddData/AddResponse")]
        System.Threading.Tasks.Task AddAsync(SnowQueen.SnowQueenService.MainModel mainModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddDataChannel : SnowQueen.SnowQueenService.IAddData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddDataClient : System.ServiceModel.ClientBase<SnowQueen.SnowQueenService.IAddData>, SnowQueen.SnowQueenService.IAddData {
        
        public AddDataClient() {
        }
        
        public AddDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(SnowQueen.SnowQueenService.MainModel mainModel) {
            base.Channel.Add(mainModel);
        }
        
        public System.Threading.Tasks.Task AddAsync(SnowQueen.SnowQueenService.MainModel mainModel) {
            return base.Channel.AddAsync(mainModel);
        }
    }
}
