//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEF.WCFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MainModel", Namespace="http://schemas.datacontract.org/2004/07/WCFService.Model")]
    [System.SerializableAttribute()]
    public partial class MainModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.IShowData")]
    public interface IShowData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowData/Show", ReplyAction="http://tempuri.org/IShowData/ShowResponse")]
        System.Collections.ObjectModel.ObservableCollection<WPFEF.WCFService.MainModel> Show();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShowData/Show", ReplyAction="http://tempuri.org/IShowData/ShowResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<WPFEF.WCFService.MainModel>> ShowAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShowDataChannel : WPFEF.WCFService.IShowData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShowDataClient : System.ServiceModel.ClientBase<WPFEF.WCFService.IShowData>, WPFEF.WCFService.IShowData {
        
        public ShowDataClient() {
        }
        
        public ShowDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShowDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShowDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShowDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WPFEF.WCFService.MainModel> Show() {
            return base.Channel.Show();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<WPFEF.WCFService.MainModel>> ShowAsync() {
            return base.Channel.ShowAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.IAddData")]
    public interface IAddData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddData/Add", ReplyAction="http://tempuri.org/IAddData/AddResponse")]
        void Add(WPFEF.WCFService.MainModel mainModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddData/Add", ReplyAction="http://tempuri.org/IAddData/AddResponse")]
        System.Threading.Tasks.Task AddAsync(WPFEF.WCFService.MainModel mainModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddDataChannel : WPFEF.WCFService.IAddData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddDataClient : System.ServiceModel.ClientBase<WPFEF.WCFService.IAddData>, WPFEF.WCFService.IAddData {
        
        public AddDataClient() {
        }
        
        public AddDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(WPFEF.WCFService.MainModel mainModel) {
            base.Channel.Add(mainModel);
        }
        
        public System.Threading.Tasks.Task AddAsync(WPFEF.WCFService.MainModel mainModel) {
            return base.Channel.AddAsync(mainModel);
        }
    }
}
